### PR TITLE
Branch percent coverage

### PR DESCRIPTION
**Pull request by juraj67**
Hi,
I added 2 columns for gcov branch coverage to the coverageTable, it contains "branch percentage" column  and "branches not covered" column: see issue #800 

image

It is possible to accept these changes ? 

Thanks in advance.

### CODE REVIEW

**Comment by zackgalbreath** [comment]
debian moved some files around so `apt-get update` was failing on Circle. Please merge master into your branch and push again.

**Comment by juraj67** [comment]
It seems ok now

**Comment by zackgalbreath** [comment]
Thanks again for working on this @juraj67. I see that the tests are passing on Circle now. Is this ready to be reviewed?

**Comment by juraj67** [comment]
Yes @zackgalbreath, I think it is ready to check

**Pull request merged**
