### PR TITLE
Move static files to outer public directory

### PR DESCRIPTION
**Pull request by williamjallen**
CDash currently has a public directory which contains symlinks to the legacy public directory.  This prevents developers from building our Docker image on Windows systems.  Most places reference the new public directory in the first place, so I have switched over the remaining references to the old paths and deleted the symlinks.

I believe I was thorough and found all of the relevant locations, but this is a difficult thing to be certain of and it is possible that I missed something.

### CODE REVIEW

**Comment by williamjallen** [comment]
Blocked until #1796 is merged into master.

**Comment by williamjallen** [comment]
This PR should be merged after CDash 3.3 is finalized to minimize risk given that it touches a lot of files

**Review by josephsnyder — CHANGES_REQUESTED** [review]
Building a test instance locally doesn't start  in my Ubuntu environment.  Webpack-cli complains that the `public/build/js` directory cannot be created:

<details open>
  <summary>docker compose -f docker/docker-compose.yml -f docker/docker-compose.postgres.yml -f docker/docker-compose.dev.yml --env-file .env.dev logs cdash</summary>

```
<snip>
cdash  | > cdash@3.2.0 production
cdash  | > mix --production
cdash  | 
cdash  | [webpack-cli] Error: ENOENT: no such file or directory, mkdir 'public/build/js'
cdash  |     at Object.mkdirSync (node:fs:1380:26)
cdash  |     at Object.<anonymous> (/cdash/webpack.mix.js:38:6)
cdash  |     at Module._compile (node:internal/modules/cjs/loader:1376:14)
cdash  |     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
cdash  |     at Module.load (node:internal/modules/cjs/loader:1207:32)
cdash  |     at Module._load (node:internal/modules/cjs/loader:1023:12)
cdash  |     at Module.require (node:internal/modules/cjs/loader:1235:19)
cdash  |     at require (node:internal/modules/helpers:176:18)
cdash  |     at module.exports (/cdash/node_modules/laravel-mix/setup/webpack.config.js:11:5)
cdash  |     at loadConfigByPath (/cdash/node_modules/webpack-cli/lib/webpack-cli.js:1439:37) {
cdash  |   errno: -2,
cdash  |   code: 'ENOENT',
cdash  |   syscall: 'mkdir',
cdash  |   path: 'public/build/js'
cdash  | }
cdash  | 
cdash  | * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
cdash  | *                            INSTALLATION FAILURE!                            *
cdash  | *                                                                             *
cdash  | * An error occurred while installing CDash and CDash was not able to recover  *
cdash  | * automatically.  If you believe that this is a problem with CDash, please    *
cdash  | * report the error here:                                                      *
cdash  | *                                                                             *
cdash  | * -> https://github.com/Kitware/CDash/issues/new                              *
cdash  | *                                                                             *
cdash  | * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
```
</details>

Looks like an update might be needed to `webpack.mix.js`?

**Comment by sbelsk** [comment]
Running 
```
docker compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml -f docker/docker-compose.postgres.yml --env-file .env.dev up -d --build
```
on Windows PowerShell seemed to work for me for building a test instance locally.

**Review by josephsnyder — APPROVED** [review]
Built system looks good.  I can't find broken images or missing fonts in a brief exploration of the system.  Error reported earlier did not reappear when building and starting up.

**Comment by josephsnyder** [comment]
@williamjallen, needs a rebase but otherwise looks good!

**Pull request merged**
