### PR TITLE
Apply all "safe" PHP migration style rules

### PR DESCRIPTION
**Pull request by williamjallen**
PHP-CS-Fixer provides a ruleset for most major and minor PHP versions which flags deprecated functions and ensures that our code style keeps up with modern PHP style guidelines.  This PR is part of a series of improvements in which I intend to gradually turn on more style check rules as we modernize the codebase.

### CODE REVIEW

**Review by josephsnyder — APPROVED** [review]
Each commit makes sense and I don't see any issue with the resulting CDash instance!

I'll leave the [documentation link about each migration] (https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/tree/master/doc/ruleSets) that you sent here so that we can find what each migration was in the future

**Comment by williamjallen** [comment]
I'll wait to rebase this until after https://github.com/Kitware/CDash/pull/1556 is merged.

**Comment by williamjallen** [comment]
@josephsnyder Resolving all of the git conflicts was difficult and resulted in invalid PHP in several places, so I simply recreated all of the changes.  I think everything should be the same as before (except that it's rebased now), but I think it's worth having an extra pair of eyes take a look before merging this.

**Review by josephsnyder — APPROVED** [review]
Things still look good! I haven't been able to find anything on my manual testing and the CI failures don't seem to be related.

**Pull request merged**
