### PR TITLE
Sequence independence

### PR DESCRIPTION
**Pull request by zackgalbreath**
We now get the same results no matter what order the XML files are parsed in.  This is another big step towards parallel submission processing.

### CODE REVIEW

**Comment by cpatrick** [comment]
If I'm reading this correctly, this accounts for different orderings, but it is not reentrant. Right?

**Comment by zackgalbreath** [comment]
I just refreshed my memory on what [reentrancy](https://en.wikipedia.org/wiki/Reentrancy_(computing)) is, but I'm still a little unclear about what you're getting at.  If the same file somehow gets processed twice concurrently?  Yeah that'll probably still cause inaccurate results.  But we have safeguards against this, at least for CDash's internal asynchronous processing system.

**Comment by cpatrick** [comment]
What I'm getting at is: If we get started with `build` and `update` at the same time, say. Is there a race condition?

**Comment by zackgalbreath** [comment]
> What I'm getting at is: If we get started with build and update at the same time, say. Is there a race condition?

Gotcha.  Yes, such a race condition exists, but it will be addressed in a followup PR that implements parallel submission processing.

**Comment by cpatrick** [comment]
In that case..

LGTM

**Pull request merged**
