### PR TITLE
Teach CDash to query GitHub for "version only" updates

### PR DESCRIPTION
**Pull request by zackgalbreath**
Allow CDash to figure out who changed what when all its given are commit IDs.  Also revamp userStatistics.php and convert it to AngularJS

### CODE REVIEW

**Comment by jamiesnape** [comment]
Can I switch this on without switching on pull request comments?

**Comment by zackgalbreath** [comment]
> Can I switch this on without switching on pull request comments?

Yes.  For CDash to comment on your PR you need to set [CTEST_CHANGE_ID](https://cmake.org/cmake/help/v3.6/variable/CTEST_CHANGE_ID.html) in your CTest driver script.  This new feature is automatic for ["version only" updates](https://cmake.org/cmake/help/v3.6/variable/CTEST_UPDATE_VERSION_ONLY.html) if your project is marked as using GitHub.  But you should also set a GitHub bot for your project to avoid getting rate limited.

**Comment by zackgalbreath** [comment]
Yes.  So far CDash only uses CTEST_CHANGE_ID to post comments on GitHub PRs.

**Comment by jamiesnape** [comment]
Ok. I guess when I put in a feature request to show CTEST_CHANGE_ID on the UI, I will ask for a toggle to switch off the bot.

LGTM.

**Pull request merged**
