### PR TITLE
Trust HTML for build errors in subproject view

### LINKED ISSUE #332: Failure to report build error
(( Ps: Thanks for all the recent improvements to CDash :smile: ))

The real build error is:

```
[  2%] Building CXX object QuickTCGA/Logic/NucleusSeg_Yi/CMakeFiles/NucleiSegLib.dir/Normalization.cpp.o
/Users/kitware/Dashboards/Nightly/S-0-E-b/SlicerPathology/QuickTCGA/Logic/NucleusSeg_Yi/Normalization.cpp:221:24: error: call to 'pow' is
      ambiguous
        LMS_ptr[j*3] = pow(10.0, log_LMS_ptr[j*3]);
                       ^~~
/Developer/SDKs/MacOSX10.6.sdk/usr/include/architecture/i386/math.h:343:15: note: candidate function
extern double pow ( double, double );
              ^
/Developer/SDKs/MacOSX10.6.sdk/usr/include/c++/4.2.1/cmath:356:3: note: candidate function
  pow(float __x, float __y)

[...]

/Developer/SDKs/MacOSX10.6.sdk/usr/include/c++/4.2.1/cmath:372:3: note: candidate function
  pow(long double __x, int __n)
  ^
3 errors generated.
make[2]: *** [QuickTCGA/Logic/NucleusSeg_Yi/CMakeFiles/NucleiSegLib.dir/Normalization.cpp.o] Error 1
make[1]: *** [QuickTCGA/Logic/NucleusSeg_Yi/CMakeFiles/NucleiSegLib.dir/all] Error 2
make: *** [all] Error 2
```

Looking at the `Build.xml`, the error is captured:

```
[...]
               <Error>
                        <BuildLogLine>10</BuildLogLine>
                        <Text>/.../SlicerPathology/QuickTCGA/Logic/NucleusSeg_Yi/Normalization.cpp:221:24: error: call to 'pow' is ambiguous</Text>
                        <SourceFile>QuickTCGA/Logic/NucleusSeg_Yi/Normalization.cpp</SourceFile>
                        <SourceLineNumber>221</SourceLineNumber>
                        <PreContext>Scanning dependencies of target ConfigureAdditionalLauncherSettings
[  1%] Configuring: AdditionalLauncherSettings.ini
[  1%] Built target ConfigureAdditionalLauncherSettings
Scanning dependencies of target NucleiSegLib
[  1%] Building CXX object QuickTCGA/Logic/NucleusSeg_Yi/CMakeFiles/NucleiSegLib.dir/BinaryMaskAnalysisFilter.cxx.o
Scanning dependencies of target CopyvtkSlicerQuickTCGAModuleLogicPythonScriptFiles
[  2%] Copying python Script: vtkSlicerQuickTCGAModuleLogic.py
[  2%] Built target CopyvtkSlicerQuickTCGAModuleLogicPythonScriptFiles
[  3%] Building CXX object QuickTCGA/Logic/NucleusSeg_Yi/CMakeFiles/NucleiSegLib.dir/Normalization.cpp.o
</PreContext>
                        <PostContext>        LMS_ptr[j*3] = pow(10.0, log_LMS_ptr[j*3]);
                       ^~~
</PostContext>
                        <RepeatCount>0</RepeatCount>
                </Error>

[...]

                <Error>
                        <BuildLogLine>31</BuildLogLine>
                        <Text>/.../SlicerPathology/QuickTCGA/Logic/NucleusSeg_Yi/Normalization.cpp:222:26: error: call to 'pow' is ambiguous</Text>
                        <SourceFile>QuickTCGA/Logic/NucleusSeg_Yi/Normalization.cpp</SourceFile>
                        <SourceLineNumber>222</SourceLineNumber>
                        <PreContext></PreContext>
                        <PostContext>        LMS_ptr[j*3+1] = pow(10.0, log_LMS_ptr[j*3+1]);
                         ^~~
</PostContext>
                        <RepeatCount>0</RepeatCount>
                </Error>

[...]
```

but CDash does not report the string `call to 'pow' is ambiguous`:

Looks like only the `Postcontext` is listed with omission of the `Text` ? 

2016 05 02_cdash_error-not-fully-reported

### PR DESCRIPTION
**Pull request by danlamanna**
@jcfr fixes #332

The API was returning the correct data for both views, however Angular only marked the embedded html as "trusted" for the individual build errors (not the subproject build errors).

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for working on this :+1: 

Bonus: Any way to also add a test to ensure no further regression is introduced ?

**Comment by danlamanna** [comment]
@jcfr Probably a good idea, should be set now.

@zackgalbreath @jamiesnape StyleCI seems to now be breaking on master? Some of the files it's reporting as broken haven't changed in months, has anyone changed the configuration?

**Comment by jcfr** [comment]
@danlamanna Thanks. As soon as the StyleCI issue is sorted out. LGTM on my side.  :+1:

**Comment by zackgalbreath** [comment]
LGTM

**Pull request merged**
