### PR TITLE
Automatically run composer update

### PR DESCRIPTION
**Pull request by zackgalbreath**
Run composer update prior to automated testing

### CODE REVIEW

**Comment by jamiesnape** [comment]
If I recall correctly, the issue here is that `composer update` writes to the `composer.lock` file that we are committing. Therefore, you are not actually testing the content of the repo if you have forgotten to run `composer update` before committing (which almost everyone does). That goes against the reason for having the `composer.lock` committed. Therefore, we should either run `composer install` or not commit `composer.lock`.

**Comment by zackgalbreath** [comment]
Thanks for the feedback, Jamie.  I just tested `composer install` on a clean source directory and I can confirm that our most recently added package gets downloaded (`random_compat`).

**Comment by jamiesnape** [comment]
Can you run `composer update` and append the new `composer.lock` file to this commit as we are out of sync and have not locked down a version of `random_compat` yet? Then LGTM.

**Comment by zackgalbreath** [comment]
The updated `composer.lock` is already included in this PR.  Merging.

**Comment by jamiesnape** [comment]
(I hate the way GitHub suppresses diffs)

**Pull request merged**
