### PR TITLE
Update recoverPassword.php to use a secure random number generator.

### PR DESCRIPTION
**Pull request by ls--**
The original implementation of recoverPassword.php uses a timestamp for
seeding the random number generator (via srand). If two people reset
their passwords at the exact same time, their passwords will be
identical. An attacker who resets their password and another users at
almost the same time can determine the approx. int value used as the
seed and then generate a list of possible passwords, iterating through
the seed values. This creates a password list that can be used to
brute-force a victims password.

This attack was tested against CDash and was found to be effective.

If you're happy with this approach, we can replace other uses of
insecure random number generators in the codebase in a similar way.

References:
http://www.openwall.com/php_mt_seed/
https://paragonie.com/blog/2015/07/how-safely-generate-random-strings-and-integers-in-php

### CODE REVIEW

**Comment by jamiesnape** [comment]
Have you ever considered [ircmaxell/random-lib](https://github.com/ircmaxell/RandomLib)? If using paragonie/random_compat, it should be installed using composer.

**Comment by ls--** [comment]
I didn't want to change too much of the CDash code, so I chose paragonie/random_compat, as it's almost a "drop in" replacement. Plus, it means that users of PHP 7 will use the native random_int function instead of an extra library.

I've added paragonie/random_compat into package.json, so Composer will install it as a dependency.

If anyone has strong preferences to change this approach, then I'm happy to modify my pull request, as long as the insecure random number generator use is fixed. :)

**Comment by jamiesnape** [comment]
Can you add paragonie/random_compat to composer.json rather than package.json?

**Comment by ls--** [comment]
Oops! I'll update it soon.

**Comment by ls--** [comment]
Updated. Thanks! :)

**Comment by jamiesnape** [comment]
LGTM.

**Pull request merged**
