### PR TITLE
Software process tooling

### PR DESCRIPTION
**Pull request by cpatrick**

### CODE REVIEW

**Comment by cpatrick** [comment]
@zackgalbreath I've turned on StyleCI for PHP style (which we broke :smiling_imp:) and added a very minimal TravisCI file that runs gulp+eslint (with the angular plugin) on the new angular js code. I can go through there and manually fix the issues, but I wanted to check with you first. It makes some really nice recommendations around angular style and semantics.

**Comment by cpatrick** [comment]
@zackgalbreath This has become a bit of a monster, but it removes PDO and most of the tests seem to work (or failed on my environment before the changes). I attempted to get the tests running on Travis, but they don't support Apache at this point for PHP... I may try CircleCI in a bit.

I'm going to base AppEngine work on the head of this branch.

**Comment by zackgalbreath** [comment]
Looks like the CDash@Home tests are failing now.  I'll see if I can figure out why.

**Comment by zackgalbreath** [comment]
False alarm, I was doing it wrong.  All tests pass for me!

**Comment by cpatrick** [comment]
I need to add some docs on the setup. I'm assuming you got composer and ran

```
php composer.phar install
```

and all that.

**Comment by zackgalbreath** [comment]
Yeah I agree that we'll need to document the new setup steps.  But rest assured that I figured it out all on my own.

**Comment by jamiesnape** [comment]
```bash
git clone https://github.com/Kitware/CDash CDash
cd CDash
curl -sS https://getcomposer.org/installer | php
php composer.phar install
```

**Comment by jamiesnape** [comment]
So long as the basic tests pass, I vote to merge this as soon as possible since it touches so much code. If it is still an issue, personally, I could live with non-functioning CI for a short while.

**Comment by cpatrick** [comment]
@zackgalbreath What do you think? Have you smoke tested this? I want your signoff before merging :smile: .

**Comment by zackgalbreath** [comment]
LGTM

**Pull request merged**
