### PR TITLE
Applied fixes from StyleCI

### PR DESCRIPTION
**Pull request by cpatrick**
This pull request applies code style fixes from an analysis carried out by [StyleCI](https://styleci.io).

---

For more information, click [here](https://styleci.io/analyses/z9056q).

### CODE REVIEW

**Comment by cpatrick** [comment]
@zackgalbreath This change was automatically generated by StyleCI and adds some sanity to the coding style. That said, it is a MONSTER. What do you think about applying it?

**Comment by cpatrick** [comment]
This would have us adhere to [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md).

**Comment by jamiesnape** [comment]
You may want to run it through the formatter in PHPStorm too. It catches issues than php-cs-fixer sometimes misses.

**Comment by zackgalbreath** [comment]
I guess the main downside is this would mess up ``git blame``, but I think that's an okay price to pay to have well-styled code.  I'm going to run an experimental build to make sure this branch doesn't inadvertently break any of our tests.

**Comment by cpatrick** [comment]
@zackgalbreath Yeah, the blame is a bit of a moot point right now anyway :sigh:.

@jamiesnape I'm just trying to establish a baseline at this point. We can get better and better as we go along. I just want to something to take the style nits out of code review so we can focus on substance. :hammer:

**Comment by zackgalbreath** [comment]
After testing locally I can confirm that this branch didn't cause any new test failures.  LGTM once the merge conflicts are resolved.

**Comment by cpatrick** [comment]
for some reason this has a ton of conflicts. I'm going to close and open another.

**Pull request closed without merging**
