### PR TITLE
No more db logging

### PR DESCRIPTION
**Pull request by cpatrick**

### CODE REVIEW

**Comment by jamiesnape** [comment]
LGTM.

**Comment by jamiesnape** [comment]
Still LGTM.

**Comment by cpatrick** [comment]
Cool. I'll merge this when circle is green.

@zackgalbreath This does remove a config. What should I do to remove the errorlog table? I can follow that up in another PR.

**Comment by jamiesnape** [comment]
A red circle is perfectly acceptable now errors do not go to the database...

**Comment by jamiesnape** [comment]
I guess you need to add to [include/upgrade_functions.php](https://github.com/Kitware/CDash/blob/master/include/upgrade_functions.php).

**Comment by zackgalbreath** [comment]
> What should I do to remove the errorlog table?

Throw a ```pdo_query("DROP TABLE IF EXISTS errorlog");``` [somewhere around here](https://github.com/Kitware/CDash/blob/master/public/upgrade.php#L718).

**Comment by cpatrick** [comment]
Do I need to doctor the .sql files?

**Comment by zackgalbreath** [comment]
> Do I need to doctor the .sql files?

Yup, remove the relevant CREATE TABLE command from both (mysql and pgsql) versions of cdash.sql.

**Comment by cpatrick** [comment]
Done.

**Comment by cpatrick** [comment]
Alright, I've really killed logging to the DB at this point. Would either of you @zackgalbreath or @jamiesnape like to bless this?

**Comment by jamiesnape** [comment]
Database.

**Comment by jamiesnape** [comment]
:bomb:

**Comment by jamiesnape** [comment]
:boom:

**Comment by jamiesnape** [comment]
LGTM.

**Comment by cpatrick** [comment]
Woo! Passing tests.

**Pull request merged**
