### PR TITLE
Add config to disable Project Administrator user registration

### PR DESCRIPTION
**Pull request by josephsnyder**
Add a new environment variable that will disable the registration form that is found on the manageProjectRoles page.  If the current user is a site administrator, the form will always be shown.

Issue: #2007

### CODE REVIEW

**Review by williamjallen — COMMENTED** [review]
Is there a pressing reason why this needs to be included in CDash 3.2 (or even 3.3, for that matter)?  At this point, I think 3.2 should only be getting the most minimal changes needed to fix urgent issues, but this looks like a new feature.  Yes, it probably would have been good to include in 3.2+, but not having it doesn't seem like a critical issue that needs to be addressed.

**Comment by josephsnyder** [comment]
@williamjallen, I made this to `releases/3.2` operating under the assumption that LLNL was sticking with `3.2.*` for a while and would want this change sooner than a `3.4` release.  I'm not against switching this to target `master` and letting Otto or Dave decide if it is important enough to be backported.

**Review by williamjallen — CHANGES_REQUESTED** [review]
The frontend looks good, but don't you also need to make some backend changes to disable the actual functionality?

**Review by williamjallen — APPROVED** [review]

**Comment by williamjallen** [comment]
Tests are failing, but good to merge once they pass.

**Pull request merged**
