### PR TITLE
Improve default Docker settings and documentation

### PR DESCRIPTION
**Pull request by zackgalbreath**

### CODE REVIEW

**Comment by zackgalbreath** [comment]
@opadron PTAL

**Comment by opadron** [comment]
I just realized that #755 hasn't landed, yet.  I'm going to *strongly* recommend that we let that land, first, rebase this over the top of that, and then I can take a pass and make a few tweaks.

**Comment by zackgalbreath** [comment]
> I just realized that #755 hasn't landed, yet. I'm going to _strongly_ recommend that we let that land, first, rebase this over the top of that, and then I can take a pass and make a few tweaks.

Agreed.  The documentation I wrote assumes #755 is the law of the land.

**Comment by zackgalbreath** [comment]
@opadron are there any changes you'd like to see before we merge this PR to master?

**Comment by opadron** [comment]
Yes, there are a few tweaks that I'd like to add.  I'll see about adding some commits here tomorrow -- preferably before I get too mixed up in SC activities! :)

**Comment by opadron** [comment]
This should be closed, since #766 continues the work.  We can reopen if needed.

**Pull request closed without merging**
