### PR TITLE
Fix insecure random number generator use

### PR DESCRIPTION
**Pull request by ls--**
Partial fix for #160, but sufficient enough to close the issue. Essentially the same fix I committed late last year, but in other areas of the codebase.

### CODE REVIEW

**Comment by ls--** [comment]
I'll fix the failed checks and update the pull request.

**Comment by ls--** [comment]
CircleCI seems to fail because of an issue unrelated to my pull request.

**Comment by zackgalbreath** [comment]
Thanks for the contribution, your time is appreciated.  I'll take a look and sort it out.

**Comment by zackgalbreath** [comment]
LGTM, tests pass locally.  Will address CircleCI as a separate issue.

**Pull request merged**
