### PR TITLE
Refactor notification/email inheritance structure

### PR DESCRIPTION
**Pull request by williamjallen**
While initially developed with good intentions, the email notification system has become a major pain point for developers due to the convoluted hierarchy of classes and interfaces.  A better solution for handling notifications is Laravel's built-in [notification system](https://laravel.com/docs/11.x/notifications).  This PR deletes many unnecessary interfaces, adds type annotations to notification code where possible, and otherwise cuts down on unnecessary technical debt.

### CODE REVIEW

**Comment by fspindle** [comment]
To be able to use `smtp` I had to modify `config/mail.php` setting `verify_peer` to `false`.

```
        'smtp' => [
            'transport' => 'smtp',
            'host' => env('MAIL_HOST', 'smtp.mailgun.org'),
            'port' => env('MAIL_PORT', 587),
            'encryption' => env('MAIL_ENCRYPTION', 'tls'),
            'username' => env('MAIL_USERNAME'),
            'password' => env('MAIL_PASSWORD'),
            'timeout' => null,
            'local_domain' => env('MAIL_EHLO_DOMAIN'),
	    'verify_peer' => false,
	],
```

**Comment by williamjallen** [comment]
@fspindle Just to clarify, that behavior is not different between my branch and master, correct?  This is a maintenance PR which should not have any effect on the current behavior.

**Comment by fspindle** [comment]
Yes, you are right. The behavior is the same as in the master branch. I just wanted to share that adding `'verify_peer' => false` makes email notification working like adding the same line to the master branch (See #2618)

**Review by josephsnyder — APPROVED** [review]
I don't send any emails from my test installation but the tests pass and the code seems in good shape.  LGTM

**Pull request merged**
