### PR TITLE
Introduce customizable URL fragments for PingIdentity

### PR DESCRIPTION
**Pull request by josephsnyder**
Add a set of customizable palces where the URL fragments used after the instance URI.
The original hard-coded values are now the defaults for the environment variables if no value is set.

### CODE REVIEW

**Review by williamjallen — COMMENTED** [review]
Are you hoping to get this into 3.4, or is this new work which should be in 3.5?

**Comment by josephsnyder** [comment]
@williamjallen, I think it would be best if this made 3.4.  But, if it needs another iteration or two, maybe it'll be best to let it slip.

**Review by williamjallen — APPROVED** [review]
Everything here looks good to me.  Given that this is a low-risk change on something which is still somewhat experimental, I'm fine with this going into 3.4 as long as it gets merged before we (hopefully) cut the release next week.

**Comment by williamjallen** [comment]
@zackgalbreath If this looks good to you, I can make the next release candidate once this gets merged.

**Review by zackgalbreath — APPROVED** [review]

**Pull request merged**
